### ISSUE TITLE
APK File

### ISSUE THREAD

**Issue by stupdude2** [Yuukari/BipTask#3]
The apk file hosted here doesn't match the one in BipTask 1.1.0.zip on myamazfit.ru and doesn't work. It confused me and might help to update the file on here too. Thanks!
https://myamazfit.ru/threads/bip-prilozhenija-dlja-bipos-elf.1174/page-75#post-50031

**Comment by yuukari** [comment]
Oh, thank you! I released version with bug, reupload it on myamazfit.ru, but forgot to update the release on GitHub
